### PR TITLE
Add badge to README.md

### PR DESCRIPTION
**Pull request by keithc-ca**
Also remove space before comma.

### CODE REVIEW

**Comment by chrisguindon** [comment]
In this situation, version 1.2 refers to the version of the Eclipse Community Code of Conduct not the version of Contributor Covenant.

**Comment by keithc-ca** [comment]
Ok, I reverted the version change in CODE_OF_CONDUCT.md (I'm sure I'm not the only one who will be mislead or confused by that).

**Comment by keithc-ca** [comment]
Is anyone interested in this? @chrisguindon?

**Comment by chrisguindon** [comment]
Our code of conduct is an adaptation of the Contributor Covenant. 

Not sure it's right for us to add this badge when it's not an exact copy of the Contributor Covenant. WDYT?

**Comment by keithc-ca** [comment]
Ideally, README.md would have more content, but I'll leave that to someone else. Closing.

**Pull request closed without merging**
